### PR TITLE
Add initial chart scale settings

### PR DESCRIPTION
**Pull request by margarita-v**
Sometimes it's important to set up the initial chart scale
Снимок экрана 2022-07-02 в 20 01 00

### CODE REVIEW

**Comment by patrykmichalik** [comment]
Hello! Cheers for your interest in contributing. Would you be able to expand on the use case here? I believe a result identical to the one in the image could be achieved by increasing the segment width. Does allowing the initial scale to be changed provide any benefit over that?

**Comment by margarita-v** [comment]
@patrykmichalik Could you elaborate how can I increase the segment width (in compose and view chart)? I'll check and maybe it would be enough

**Comment by patrykmichalik** [comment]
Sure. In the case of line charts, you can bump up the point spacing. In Compose, thatʼd look like so: `lineChart(spacing = 64.dp, ...)`. In the view system, you could use this: `(chartView.chart as LineChart).spacingDp = 32f` (where `chartView` is a reference to your `ChartView` instance). For column charts, you can set the column width, the spacing between multiple columns in a single segment, and the spacing between the edges of each segment and the column or columns it contains.

**Comment by margarita-v** [comment]
@patrykmichalik Thank you, it helps :) I think that PR should be closed

**Comment by patrykmichalik** [comment]
You’re welcome, and thanks again!

**Pull request closed without merging**
